version: '3.7'
services:
    nginx-proxy:
        image:jwilder/nginx-proxy
        network_mode:bridge
web:
 image: 
     nginx:latest
ports:
- "8080:80"
volumes:
 - ./src:/usr/share/nginx/html
links:
 - php
php:
 image: 
     php:7-fpm
