# spring with host path Volume
apiVersion: v1
kind: ReplicationController
metadata:
    labels:
     name: springboot
    name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dilberzaman/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080
---
# Node Port sevice
apiVersion: v1
kind: Service
metadata:
  labels:
   name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: springboot
---
#mongo host path
apiVersion: v1
kind: ReplicationController
metadata:
    labels:
     name: mongo
    name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          hostPath:
            path: /tmp/dbbackup
---
#mongo Node port
apiVersion: v1
kind: Service
metadata:
  labels:
   name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo
